name: persian_range_date_picker
description: A persian (farsi,shamsi) datetime picker for flutter, inspired by material datetime picker.
version: 1.0.0
homepage: https://github.com/tech-ninja-ir/persian-datetime-picker

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  shamsi_date: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

